name: cd
on:
  push:
    tags:
    - "v*"

jobs:
  plugin-cd:
    uses: mattermost/actions-workflows/.github/workflows/community-plugin-cd.yml@86a78bd5bf6e009254bd0e23e316601d9d0db472
    secrets: inherit
    permissions:
      contents: write
