name: ci
on:
  pull_request:
  push:
    branches:
    - master
    - main

jobs:
  plugin-ci:
    uses: mattermost/actions-workflows/.github/workflows/community-plugin-ci.yml@86a78bd5bf6e009254bd0e23e316601d9d0db472
    secrets: inherit
